import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Navbar/NavBar'
import "@uploadthing/react/styles.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={`${inter.className} bg-gray-100` }>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
